Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "SFTPServer"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "SFTPServer"
      vb.memory = "512"
      vb.cpus = "2"
      vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
    end

    config.vm.network "private_network", ip: "192.168.2.4"
    config.vm.provision "shell", path: "Provision/config.sh"
end