Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "WS-Python"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "WS-Python"
      vb.memory = "512"
      vb.cpus = "2"
      vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
    end
  
    config.vm.network "private_network", ip: "192.168.2.6"
    config.vm.synced_folder "App/", "/var/www/", 
      owner: "www-data", group: "www-data"
    config.vm.provision "shell", path: "Config/config.sh"
end