Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "Docker"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Docker"
    vb.memory = "512"
    vb.cpus = "2"
  end
  
  config.vm.network "private_network", ip: "192.168.2.5"
  config.vm.provision "shell", path: "Config/config.sh"
end